In [2]:
import numpy as np

def generateX(dataSize):
    x=np.random.uniform(1,-1,dataSize)
    return x

def sign(x):
    if x<=0:
        return -1
    if x>0:
        return 1

def generateY(x,dataSize,noise_rate):
    #get s(x)
    i=0
    y=np.zeros(dataSize)
    for i in range(dataSize):
        y[i]=sign(x[i])
    
    #get noise
    j=0
    randomList=[]
    randomList=np.random.rand(dataSize)
    for j in range(dataSize):
        if (randomList[j]/np.max(randomList))<noise_rate:
            y[j]=-y[j]
    
    return y

def generateTheta(x):
    Xlen=len(x)
    xList=sorted(x)
    theta=np.zeros(Xlen)
    
    for i in range(Xlen-1):
        theta[i]=(xList[i]+xList[i+1])/2
        
    theta[-1]=1
    
    return theta

def caculateError(x,y,theta,s):
    nx=len(x)
    error=0
    for i in range(nx):
        temp=s*sign(x[i]-theta)
        if temp!=y[i]:
            error=error+1
    return error

def deciStump(X,Y,exTimes):
    for j in range(exTimes):
        dataSize=len(X)
        theta=generateTheta(X)
        Y=generateY(X,dataSize,noiseRate)
        e_in=np.zeros((2,dataSize))
    for i in range(len(theta)):
        e_in[0][i]=caculateError(X,Y,theta[i],1)/dataSize
        e_in[1][i]=caculateError(X,Y,theta[i],-1)/dataSize
    s=0
    theta_best=0
    
    mins1, mins01=np.min(e_in[0]), np.min(e_in[1])
    if mins1<mins01:
        s=1
        theta_best=theta[np.argmin(e_in[0])]
    
    else:
        s=-1
        theta_best=theta[np.argmin(e_in[1])]
        
    e_out=0.5+0.3*s*(np.abs(theta_best)-1)
    
    E_in=E_in+np.min(e_in)
    E_out=E_out+np.min(e_out)
    
    return E_in, E_out
    
dataSize=20
noiseRate=0.2
exTimes=5000
E_in=0
E_out=0

for j in range(exTimes):
    X=generateX(dataSize)
    theta=generateTheta(X)
    Y=generateY(X,dataSize,noiseRate)
    
    e_in=np.zeros((2,dataSize))
    for i in range(len(theta)):
        e_in[0][i]=caculateError(X,Y,theta[i],1)/dataSize
        e_in[1][i]=caculateError(X,Y,theta[i],-1)/dataSize
    
    s=0
    theta_best=0
    
    mins1, mins01=np.min(e_in[0]), np.min(e_in[1])
    if mins1<mins01:
        s=1
        theta_best=theta[np.argmin(e_in[0])]
    
    else:
        s=-1
        theta_best=theta[np.argmin(e_in[1])]
        
    e_out=0.5+0.3*s*(np.abs(theta_best)-1)
    
    E_in=E_in+np.min(e_in)
    E_out=E_out+np.min(e_out)

avg_Ein=E_in/exTimes
avg_Eout=E_out/exTimes

print(avg_Ein,avg_Eout)




        
        
    
    

    

0.1617900000000007 0.2541701449207941


In [5]:
import numpy as np
randomList=np.random.rand(5)

In [7]:
print(np.max(randomList))

0.968793425956519


In [14]:
import numpy as np
n=np.zeros(5)
n[-1]=1
print(n[-1])

1.0


In [ ]:
#multi-decision stump

In [58]:
import numpy as np

def generateX(dataSize):
    x=np.random.uniform(1,-1,dataSize)
    return x

def sign(x):
    if x<=0:
        return -1
    if x>0:
        return 1

def generateY(x,dataSize,noise_rate):
    #get s(x)
    i=0
    y=np.zeros(dataSize)
    for i in range(dataSize):
        y[i]=sign(x[i])
    
    #get noise
    j=0
    randomList=[]
    randomList=np.random.rand(dataSize)
    for j in range(dataSize):
        if (randomList[j]/np.max(randomList))<noise_rate:
            y[j]=-y[j]
    
    return y

def generateTheta(x):
    Xlen=len(x)
    xList=sorted(x)
    theta=np.zeros(Xlen)
    
    for i in range(Xlen-1):
        theta[i]=(xList[i]+xList[i+1])/2
        
    theta[-1]=1
    
    return theta

def caculateError(x,y,theta,s):
    nx=len(x)
    error=0
    for i in range(nx):
        temp=s*sign(x[i]-theta)
        if temp!=y[i]:
            error=error+1
    return error

def deciStump(X,Y,exTimes):
    E_in=0
    E_out=0
    for j in range(exTimes):
        print(j)
        dataSize=len(X)
        theta=generateTheta(X)
        e_in=np.zeros((2,dataSize))
        for i in range(len(theta)):
            e_in[0][i]=caculateError(X,Y,theta[i],1)/dataSize
            e_in[1][i]=caculateError(X,Y,theta[i],-1)/dataSize
            s=0
            theta_best=0
        
        mins1, mins01=np.min(e_in[0]), np.min(e_in[1])
        if mins1<mins01:
            s=1
            theta_best=theta[np.argmin(e_in[0])]
        else:
            s=-1
            theta_best=theta[np.argmin(e_in[1])]
            
        e_out=0.5+0.3*s*(np.abs(theta_best)-1)
        E_in=E_in+np.min(e_in)
        E_out=E_out+np.min(e_out)
    
    avg_Ein=E_in/exTimes
    avg_Eout=E_out/exTimes
    return avg_Ein, avg_Eout

def getData(file_root):
    b=np.array(np.loadtxt('hw2_train.dat.txt'))
    dataShape=b.shape
    xLen=b.shape[1]-1
    xNum=b.shape[0]
    X=b[:,0:xLen]
    Y=b[:,xLen:xLen+1]
    
    return X,Y

def getXi(X,i):
    Xi=X[:,i]
    Xi=np.transpose(Xi)
    
    return Xi

file_root_train="hw2_train.dat.txt"
file_root_test="hw2_test.dat.txt"

exTimes=100
noiseRate=0.2


X_train,Y_train=getData(file_root_train)

E_in1=np.zeros((1,X_train.shape[1]))
E_out1=np.zeros((1,X_train.shape[1]))
#print(X_train.shape[1])
for i in range(X_train.shape[1]):
    Xi=getXi(X_train,i)
    E_in1[0,i],E_out1[0,i]=deciStump(Xi,Y_train,exTimes)

print(np.min(E_in1),np.min(E_out1))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46

In [28]:
import numpy as np
b=[[2,3,5,6],[3,4,7,8],[6,6,1,1]]
b=np.array(b)
dsahpe=b.shape
print(dsahpe[0])
print(len(b))
print(b[:,0:dsahpe[1]])

3
3
[[2 3 5 6]
 [3 4 7 8]
 [6 6 1 1]]


In [57]:
print(E_in1)

[[0.36 0.   0.   0.   0.   0.   0.   0.   0.  ]]


In [ ]:
X_test,Y_test=getData(file_root_test)
E_in2=np.zeros((1,X_test.shape[1]))
E_out2=np.zeros((1,X_test.shape[1]))
#print(X_train.shape[1])
for i in range(X_test.shape[1]):
    Xi=getXi(X_test,i)
    E_in2[0,i],E_out2[0,i]=deciStump(Xi,Y_test,exTimes)

print(np.min(E_in2),np.min(E_out2))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46