In [1]:
import numpy as np
import math

def sign(x1,x2):
    if x1**2+x2**2-0.6<=0:
        return -1
    else:
        return 1

def calError(feature,w,y):
    errorCount=0
    for i in range(len(y)):
        if np.dot(feature[i],w)*y[i]<0:
            errorCount += 1
    
    return errorCount/len(y)

def getData(file_root):
    b=np.array(np.loadtxt(file_root))
    dataShape=b.shape
    xLen=b.shape[1]-1
    xNum=b.shape[0]
    X=b[:,0:xLen]
    #
    Xnew=np.ones((dataShape))
    Xnew[:,1:len(Xnew[0])]=X
    Y=b[:,xLen:xLen+1]
    
    return Xnew,Y

def getXi(X,i):
    Xi=X[:,i]
    Xi=np.transpose(Xi)
    
    return Xi

def fixedGD(x,y,w):
    temp=-y*(np.dot(x,w))
    theta=np.exp(temp)/(1+np.exp(temp))
    gradient=(1/len(x))*(sum(theta*-y*x).reshape(len(w), 1))
    return gradient

def sgd(x,y,w):
    temp=-y*(np.dot(x,w))
    theta=np.exp(temp)/(1+np.exp(temp))
    gradient=np.mat(theta*y*x)
    print(gradient)
    gradient=gradient.reshape(len(w), 1)
    print(gradient)
    return gradient



In [17]:

a=[[2,3,4],[5,6,7]]

print([1,a])

[1, [[2, 3, 4], [5, 6, 7]]]


In [47]:
##18

#0 parameters
file_root_train='hw3_train.dat.txt'
file_root_test='hw3_test.dat.txt'
ita=0.001
exTimes=2000

## Train
#1 getDataset
X_train,Y_train=getData(file_root_train)
X_test,Y_test=getData(file_root_test)
#2 get W
W=np.zeros((len(X_train[0]),1))

#3 logistic regression
for i in range(exTimes):
    W=W-ita*fixedGD(X_train,Y_train,W)
    print(i)

error_rate=calError(X_test,W,Y_test)
print(W)
print(error_rate)

[[ 0.01878417]
 [-0.01260595]
 [ 0.04084862]
 [-0.03266317]
 [ 0.01502334]
 [-0.03667437]
 [ 0.01255934]
 [ 0.04815065]
 [-0.02206419]
 [ 0.02479605]
 [ 0.06899284]
 [ 0.0193719 ]
 [-0.01988549]
 [-0.0087049 ]
 [ 0.04605863]
 [ 0.05793382]
 [ 0.061218  ]
 [-0.04720391]
 [ 0.06070375]
 [-0.01610907]
 [-0.03484607]]
0.475


In [48]:
##19
file_root_train='hw3_train.dat.txt'
file_root_test='hw3_test.dat.txt'
ita=0.01
exTimes=2000

## Train
#1 getDataset
X_train,Y_train=getData(file_root_train)
X_test,Y_test=getData(file_root_test)
#2 get W
W=np.zeros((len(X_train[0]),1))

#3 logistic regression
for i in range(exTimes):
    W=W-ita*fixedGD(X_train,Y_train,W)
    print(i)

error_rate=calError(X_test,W,Y_test)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999


In [49]:
print(W)
print(error_rate)

[[-0.00385379]
 [-0.18914564]
 [ 0.26625908]
 [-0.35356593]
 [ 0.04088776]
 [-0.3794296 ]
 [ 0.01982783]
 [ 0.33391527]
 [-0.26386754]
 [ 0.13489328]
 [ 0.4914191 ]
 [ 0.08726107]
 [-0.25537728]
 [-0.16291797]
 [ 0.30073678]
 [ 0.40014954]
 [ 0.43218808]
 [-0.46227968]
 [ 0.43230193]
 [-0.20786372]
 [-0.36936337]]
0.22


In [50]:
##20

In [2]:

file_root_train='hw3_train.dat.txt'
file_root_test='hw3_test.dat.txt'
ita=0.001
exTimes=2000

## Train
#1 getDataset
X_train,Y_train=getData(file_root_train)
X_test,Y_test=getData(file_root_test)
#2 get W
W=np.zeros((len(X_train[0]),1))
index=0
#3 logistic regression
for i in range(exTimes):
    if index>len(X_train):
        index=0
    W=W+ita*sgd(X_train[index],Y_train[index],W)
    index=index+1
    print(i)

error_rate=calError(X_test,W,Y_test)

[[0.5        0.28774    0.26969    0.361555   0.11851    0.47932
  0.42604    0.34321    0.177155   0.00477175 0.467615   0.10828
  0.310535   0.156855   0.413375   0.308275   0.08734    0.060045
  0.191585   0.17757    0.197195  ]]
[[0.5       ]
 [0.28774   ]
 [0.26969   ]
 [0.361555  ]
 [0.11851   ]
 [0.47932   ]
 [0.42604   ]
 [0.34321   ]
 [0.177155  ]
 [0.00477175]
 [0.467615  ]
 [0.10828   ]
 [0.310535  ]
 [0.156855  ]
 [0.413375  ]
 [0.308275  ]
 [0.08734   ]
 [0.060045  ]
 [0.191585  ]
 [0.17757   ]
 [0.197195  ]]
0
[[0.49921172 0.35307747 0.44181735 0.31331526 0.46851519 0.10416053
  0.41054173 0.03994193 0.11172858 0.09459563 0.28823486 0.19753309
  0.44725376 0.1852375  0.35924773 0.27865998 0.03385704 0.14512584
  0.19475248 0.34372724 0.03847724]]
[[0.49921172]
 [0.35307747]
 [0.44181735]
 [0.31331526]
 [0.46851519]
 [0.10416053]
 [0.41054173]
 [0.03994193]
 [0.11172858]
 [0.09459563]
 [0.28823486]
 [0.19753309]
 [0.44725376]
 [0.1852375 ]
 [0.35924773]
 [0.27865998]
 [0.0

54
[[0.49658005 0.02458071 0.13834224 0.14783188 0.41079585 0.29278856
  0.23568186 0.33555404 0.49498106 0.349354   0.34209896 0.21076347
  0.3689987  0.19445578 0.08915102 0.3699869  0.45934648 0.19098469
  0.2992888  0.13047144 0.21821714]]
[[0.49658005]
 [0.02458071]
 [0.13834224]
 [0.14783188]
 [0.41079585]
 [0.29278856]
 [0.23568186]
 [0.33555404]
 [0.49498106]
 [0.349354  ]
 [0.34209896]
 [0.21076347]
 [0.3689987 ]
 [0.19445578]
 [0.08915102]
 [0.3699869 ]
 [0.45934648]
 [0.19098469]
 [0.2992888 ]
 [0.13047144]
 [0.21821714]]
55
[[-0.50235953 -0.38904731 -0.10514385 -0.29167999 -0.37055044 -0.49261375
  -0.20915739 -0.17156583 -0.43186844 -0.20390773 -0.11634144 -0.00964028
  -0.40820228 -0.32808598 -0.18508934 -0.06287532 -0.36645621 -0.26137264
  -0.10659064 -0.34270465 -0.00448768]]
[[-0.50235953]
 [-0.38904731]
 [-0.10514385]
 [-0.29167999]
 [-0.37055044]
 [-0.49261375]
 [-0.20915739]
 [-0.17156583]
 [-0.43186844]
 [-0.20390773]
 [-0.11634144]
 [-0.00964028]
 [-0.40820228]
 

 [-0.34030939]]
137
[[-0.50808544 -0.24882976 -0.10343095 -0.12250956 -0.2002822  -0.44431055
  -0.2891311  -0.45582377 -0.30578106 -0.15762334 -0.15446813 -0.02075173
  -0.49677545 -0.21191227 -0.31942823 -0.0452191  -0.44275073 -0.47430792
  -0.11348596 -0.4080739  -0.29896255]]
[[-0.50808544]
 [-0.24882976]
 [-0.10343095]
 [-0.12250956]
 [-0.2002822 ]
 [-0.44431055]
 [-0.2891311 ]
 [-0.45582377]
 [-0.30578106]
 [-0.15762334]
 [-0.15446813]
 [-0.02075173]
 [-0.49677545]
 [-0.21191227]
 [-0.31942823]
 [-0.0452191 ]
 [-0.44275073]
 [-0.47430792]
 [-0.11348596]
 [-0.4080739 ]
 [-0.29896255]]
138
[[0.49124118 0.20167907 0.30233438 0.2184353  0.4755755  0.14285785
  0.076388   0.13020839 0.00268729 0.39426526 0.02708114 0.38657242
  0.15963865 0.32293704 0.45226611 0.30066908 0.42013893 0.38071683
  0.17700402 0.27144514 0.41772203]]
[[0.49124118]
 [0.20167907]
 [0.30233438]
 [0.2184353 ]
 [0.4755755 ]
 [0.14285785]
 [0.076388  ]
 [0.13020839]
 [0.00268729]
 [0.39426526]
 [0.02708114]
 [0

 [-0.08034672]]
187
[[-0.51320016 -0.40369864 -0.24710587 -0.31399125 -0.05049325 -0.28257314
  -0.35233757 -0.08670517 -0.47236482 -0.36170347 -0.19872136 -0.10097726
  -0.10436438 -0.32393707 -0.25265357 -0.19355857 -0.18150863 -0.34042106
  -0.33146058 -0.33457571 -0.00907851]]
[[-0.51320016]
 [-0.40369864]
 [-0.24710587]
 [-0.31399125]
 [-0.05049325]
 [-0.28257314]
 [-0.35233757]
 [-0.08670517]
 [-0.47236482]
 [-0.36170347]
 [-0.19872136]
 [-0.10097726]
 [-0.10436438]
 [-0.32393707]
 [-0.25265357]
 [-0.19355857]
 [-0.18150863]
 [-0.34042106]
 [-0.33146058]
 [-0.33457571]
 [-0.00907851]]
188
[[0.48348562 0.30104232 0.47440093 0.07328675 0.14824636 0.02138215
  0.43770437 0.36423873 0.14011897 0.3556907  0.29343226 0.26277444
  0.32146959 0.44876652 0.0033976  0.36739589 0.0435901  0.40994263
  0.48284742 0.39191828 0.29109702]]
[[0.48348562]
 [0.30104232]
 [0.47440093]
 [0.07328675]
 [0.14824636]
 [0.02138215]
 [0.43770437]
 [0.36423873]
 [0.14011897]
 [0.3556907 ]
 [0.29343226]
 [0

 [-0.29635051]]
231
[[-0.5118668  -0.32532718 -0.15246465 -0.48275694 -0.48322785 -0.37948269
  -0.34061153 -0.27154022 -0.15384157 -0.30997118 -0.32567013 -0.13779454
  -0.127117   -0.15529527 -0.44350187 -0.36342543 -0.18122132 -0.27059838
  -0.05306523 -0.36831888 -0.27209304]]
[[-0.5118668 ]
 [-0.32532718]
 [-0.15246465]
 [-0.48275694]
 [-0.48322785]
 [-0.37948269]
 [-0.34061153]
 [-0.27154022]
 [-0.15384157]
 [-0.30997118]
 [-0.32567013]
 [-0.13779454]
 [-0.127117  ]
 [-0.15529527]
 [-0.44350187]
 [-0.36342543]
 [-0.18122132]
 [-0.27059838]
 [-0.05306523]
 [-0.36831888]
 [-0.27209304]]
232
[[0.48891157 0.36255726 0.28531901 0.39962165 0.06831072 0.25131032
  0.32038864 0.16124792 0.31232649 0.22616071 0.22774967 0.46654875
  0.03653441 0.42643356 0.48577764 0.26123523 0.14814998 0.01203651
  0.00714202 0.0475667  0.00491503]]
[[0.48891157]
 [0.36255726]
 [0.28531901]
 [0.39962165]
 [0.06831072]
 [0.25131032]
 [0.32038864]
 [0.16124792]
 [0.31232649]
 [0.22616071]
 [0.22774967]
 [0

 [0.48170068]]
278
[[0.48963805 0.05360557 0.4184104  0.21665504 0.08389948 0.34555715
  0.4158398  0.17298912 0.27388394 0.10530645 0.11602953 0.14092273
  0.15860356 0.31104257 0.3256142  0.28669287 0.27143575 0.11515797
  0.17380682 0.33234672 0.25822042]]
[[0.48963805]
 [0.05360557]
 [0.4184104 ]
 [0.21665504]
 [0.08389948]
 [0.34555715]
 [0.4158398 ]
 [0.17298912]
 [0.27388394]
 [0.10530645]
 [0.11602953]
 [0.14092273]
 [0.15860356]
 [0.31104257]
 [0.3256142 ]
 [0.28669287]
 [0.27143575]
 [0.11515797]
 [0.17380682]
 [0.33234672]
 [0.25822042]]
279
[[-0.51445911 -0.28929579 -0.11003251 -0.06232672 -0.36626402 -0.08170125
  -0.30593854 -0.49496626 -0.43263439 -0.17193738 -0.31060469 -0.40652044
  -0.42573035 -0.15657049 -0.33221197 -0.45304813 -0.23596696 -0.49416884
  -0.46972175 -0.0620129  -0.05206326]]
[[-0.51445911]
 [-0.28929579]
 [-0.11003251]
 [-0.06232672]
 [-0.36626402]
 [-0.08170125]
 [-0.30593854]
 [-0.49496626]
 [-0.43263439]
 [-0.17193738]
 [-0.31060469]
 [-0.40652044]

325
[[-0.51462817 -0.51198299 -0.05512182 -0.4258085  -0.38827152 -0.00584772
  -0.19473016 -0.1629107  -0.22756858 -0.35655498 -0.3820651  -0.30259107
  -0.42457854 -0.10675961 -0.31292995 -0.26175533 -0.40547039 -0.17310548
  -0.49620449 -0.19127185 -0.01221213]]
[[-0.51462817]
 [-0.51198299]
 [-0.05512182]
 [-0.4258085 ]
 [-0.38827152]
 [-0.00584772]
 [-0.19473016]
 [-0.1629107 ]
 [-0.22756858]
 [-0.35655498]
 [-0.3820651 ]
 [-0.30259107]
 [-0.42457854]
 [-0.10675961]
 [-0.31292995]
 [-0.26175533]
 [-0.40547039]
 [-0.17310548]
 [-0.49620449]
 [-0.19127185]
 [-0.01221213]]
326
[[0.48587771 0.17026127 0.09802583 0.1725206  0.21909198 0.27234903
  0.02734228 0.22457268 0.37538912 0.38588894 0.4471241  0.48081486
  0.18543037 0.02396009 0.43668745 0.41591132 0.29404833 0.31459124
  0.35360722 0.07814371 0.17181608]]
[[0.48587771]
 [0.17026127]
 [0.09802583]
 [0.1725206 ]
 [0.21909198]
 [0.27234903]
 [0.02734228]
 [0.22457268]
 [0.37538912]
 [0.38588894]
 [0.4471241 ]
 [0.48081486]
 [0.1

[[-0.51137643 -0.45201074 -0.34459612 -0.1691173  -0.00719404 -0.31720169
  -0.08213217 -0.13725855 -0.28211104 -0.13067713 -0.24355837 -0.27692568
  -0.50217166 -0.45748247 -0.04708141 -0.46575143 -0.46290306 -0.36763363
  -0.22277603 -0.45912399 -0.29788189]]
[[-0.51137643]
 [-0.45201074]
 [-0.34459612]
 [-0.1691173 ]
 [-0.00719404]
 [-0.31720169]
 [-0.08213217]
 [-0.13725855]
 [-0.28211104]
 [-0.13067713]
 [-0.24355837]
 [-0.27692568]
 [-0.50217166]
 [-0.45748247]
 [-0.04708141]
 [-0.46575143]
 [-0.46290306]
 [-0.36763363]
 [-0.22277603]
 [-0.45912399]
 [-0.29788189]]
385
[[0.48945646 0.14857451 0.05431498 0.18699195 0.04250391 0.24802717
  0.09335403 0.45474421 0.16048788 0.20272308 0.14506511 0.40521122
  0.28163814 0.12837954 0.29418781 0.33416661 0.095816   0.24902566
  0.28939603 0.12614272 0.37016124]]
[[0.48945646]
 [0.14857451]
 [0.05431498]
 [0.18699195]
 [0.04250391]
 [0.24802717]
 [0.09335403]
 [0.45474421]
 [0.16048788]
 [0.20272308]
 [0.14506511]
 [0.40521122]
 [0.28163

  0.34228279 0.13919211 0.17905253]]
[[0.48758927]
 [0.45804136]
 [0.43332546]
 [0.12476434]
 [0.11847932]
 [0.47377099]
 [0.02626595]
 [0.35717376]
 [0.24981148]
 [0.24231724]
 [0.47471691]
 [0.4338228 ]
 [0.13719787]
 [0.22159469]
 [0.27243563]
 [0.10194516]
 [0.03546724]
 [0.21087748]
 [0.34228279]
 [0.13919211]
 [0.17905253]]
455
[[0.48461317 0.38693938 0.4012694  0.36742886 0.01787156 0.35606468
  0.21625863 0.07440751 0.32970172 0.37642812 0.36559702 0.1909279
  0.26962907 0.36850955 0.47574475 0.02571842 0.40001909 0.0130075
  0.46535464 0.33878337 0.14096912]]
[[0.48461317]
 [0.38693938]
 [0.4012694 ]
 [0.36742886]
 [0.01787156]
 [0.35606468]
 [0.21625863]
 [0.07440751]
 [0.32970172]
 [0.37642812]
 [0.36559702]
 [0.1909279 ]
 [0.26962907]
 [0.36850955]
 [0.47574475]
 [0.02571842]
 [0.40001909]
 [0.0130075 ]
 [0.46535464]
 [0.33878337]
 [0.14096912]]
456
[[-0.51297541 -0.42647237 -0.36916275 -0.1689741  -0.1810598  -0.12040559
  -0.32374904 -0.24503296 -0.31402303 -0.24319138 -0

491
[[-0.51740428 -0.31805359 -0.50718037 -0.11360128 -0.0377731  -0.17161265
  -0.18611032 -0.08907632 -0.07425269 -0.19603931 -0.04036995 -0.26647873
  -0.45452931 -0.09136842 -0.43119956 -0.25003562 -0.3674657  -0.48572879
  -0.16652657 -0.43913136 -0.4724315 ]]
[[-0.51740428]
 [-0.31805359]
 [-0.50718037]
 [-0.11360128]
 [-0.0377731 ]
 [-0.17161265]
 [-0.18611032]
 [-0.08907632]
 [-0.07425269]
 [-0.19603931]
 [-0.04036995]
 [-0.26647873]
 [-0.45452931]
 [-0.09136842]
 [-0.43119956]
 [-0.25003562]
 [-0.3674657 ]
 [-0.48572879]
 [-0.16652657]
 [-0.43913136]
 [-0.4724315 ]]
492
[[-0.52629465 -0.23090125 -0.39745772 -0.38589503 -0.0439956  -0.19253437
  -0.36715367 -0.23408533 -0.36096971 -0.36350119 -0.34238098 -0.40736785
  -0.51401093 -0.30880865 -0.29360926 -0.43434045 -0.37248504 -0.04519818
  -0.42386718 -0.5138741  -0.38965277]]
[[-0.52629465]
 [-0.23090125]
 [-0.39745772]
 [-0.38589503]
 [-0.0439956 ]
 [-0.19253437]
 [-0.36715367]
 [-0.23408533]
 [-0.36096971]
 [-0.36350119]
 [

 [0.08224241]]
574
[[-0.51481265 -0.37937573 -0.03986503 -0.05433333 -0.50152533 -0.14752471
  -0.07306221 -0.47430719 -0.17860395 -0.36776156 -0.23416768 -0.19255537
  -0.44266165 -0.32425474 -0.28115463 -0.474266   -0.0303549  -0.26514396
  -0.01595301 -0.4678257  -0.24209579]]
[[-0.51481265]
 [-0.37937573]
 [-0.03986503]
 [-0.05433333]
 [-0.50152533]
 [-0.14752471]
 [-0.07306221]
 [-0.47430719]
 [-0.17860395]
 [-0.36776156]
 [-0.23416768]
 [-0.19255537]
 [-0.44266165]
 [-0.32425474]
 [-0.28115463]
 [-0.474266  ]
 [-0.0303549 ]
 [-0.26514396]
 [-0.01595301]
 [-0.4678257 ]
 [-0.24209579]]
575
[[0.48052237 0.19903236 0.08629221 0.09707032 0.07964658 0.10657025
  0.47093594 0.24799279 0.00923035 0.27931804 0.10856922 0.0581336
  0.26425366 0.4553526  0.39546991 0.38475426 0.45214271 0.27170657
  0.33810515 0.34516402 0.45168622]]
[[0.48052237]
 [0.19903236]
 [0.08629221]
 [0.09707032]
 [0.07964658]
 [0.10657025]
 [0.47093594]
 [0.24799279]
 [0.00923035]
 [0.27931804]
 [0.10856922]
 [0.0

 [0.31380618]]
650
[[0.48142451 0.04841205 0.23576803 0.23975904 0.32912587 0.24777957
  0.2082161  0.25882826 0.22861406 0.20088882 0.39784922 0.09242869
  0.15639075 0.21124426 0.03996497 0.39575984 0.09328563 0.03789485
  0.18043791 0.04307883 0.20435026]]
[[0.48142451]
 [0.04841205]
 [0.23576803]
 [0.23975904]
 [0.32912587]
 [0.24777957]
 [0.2082161 ]
 [0.25882826]
 [0.22861406]
 [0.20088882]
 [0.39784922]
 [0.09242869]
 [0.15639075]
 [0.21124426]
 [0.03996497]
 [0.39575984]
 [0.09328563]
 [0.03789485]
 [0.18043791]
 [0.04307883]
 [0.20435026]]
651
[[-5.17443220e-01 -4.03574665e-01 -1.03938820e-01 -2.05295598e-04
  -1.15529548e-01 -4.24303441e-01 -2.91025590e-01 -1.01506837e-01
  -2.05238679e-02 -4.42279418e-01 -2.90451228e-01 -3.06466096e-01
  -2.77572067e-01 -3.58262162e-01 -6.00699835e-04 -1.86362350e-01
  -4.82774525e-01 -3.61066705e-01 -5.13924606e-01 -4.49720252e-01
  -3.58877920e-01]]
[[-5.17443220e-01]
 [-4.03574665e-01]
 [-1.03938820e-01]
 [-2.05295598e-04]
 [-1.15529548e-

741
[[-0.52664785 -0.16933308 -0.19902022 -0.22880743 -0.46545137 -0.39389573
  -0.01303664 -0.32028616 -0.27521037 -0.22223486 -0.02723665 -0.21655233
  -0.21015356 -0.48125607 -0.01603221 -0.15392863 -0.39651317 -0.01037075
  -0.25565593 -0.36581486 -0.02728668]]
[[-0.52664785]
 [-0.16933308]
 [-0.19902022]
 [-0.22880743]
 [-0.46545137]
 [-0.39389573]
 [-0.01303664]
 [-0.32028616]
 [-0.27521037]
 [-0.22223486]
 [-0.02723665]
 [-0.21655233]
 [-0.21015356]
 [-0.48125607]
 [-0.01603221]
 [-0.15392863]
 [-0.39651317]
 [-0.01037075]
 [-0.25565593]
 [-0.36581486]
 [-0.02728668]]
742
[[0.46712357 0.13694195 0.00975261 0.00956903 0.11186208 0.39164574
  0.27685012 0.14186076 0.01391281 0.10784015 0.42454993 0.36337542
  0.28092344 0.44951301 0.30602666 0.31858762 0.41578669 0.2972681
  0.12240506 0.21786176 0.31215065]]
[[0.46712357]
 [0.13694195]
 [0.00975261]
 [0.00956903]
 [0.11186208]
 [0.39164574]
 [0.27685012]
 [0.14186076]
 [0.01391281]
 [0.10784015]
 [0.42454993]
 [0.36337542]
 [0.28

[[-0.53854734]
 [-0.06277308]
 [-0.35279698]
 [-0.28959845]
 [-0.53614542]
 [-0.24440355]
 [-0.51153381]
 [-0.43778513]
 [-0.37978897]
 [-0.29568942]
 [-0.51757631]
 [-0.05956334]
 [-0.47721757]
 [-0.10029367]
 [-0.13334971]
 [-0.05152121]
 [-0.33103428]
 [-0.23387495]
 [-0.26176094]
 [-0.39591308]
 [-0.00133199]]
824
[[0.47067959 0.19771838 0.28766054 0.1428795  0.31366088 0.13662417
  0.28005436 0.17049427 0.35462413 0.06092947 0.06643642 0.1874858
  0.04633323 0.08799826 0.06332053 0.19151482 0.44608188 0.2473939
  0.31390093 0.31282307 0.3115946 ]]
[[0.47067959]
 [0.19771838]
 [0.28766054]
 [0.1428795 ]
 [0.31366088]
 [0.13662417]
 [0.28005436]
 [0.17049427]
 [0.35462413]
 [0.06092947]
 [0.06643642]
 [0.1874858 ]
 [0.04633323]
 [0.08799826]
 [0.06332053]
 [0.19151482]
 [0.44608188]
 [0.2473939 ]
 [0.31390093]
 [0.31282307]
 [0.3115946 ]]
825
[[-0.52321647 -0.07464206 -0.11553143 -0.48369793 -0.25639177 -0.37899709
  -0.34931501 -0.1094098  -0.27984233 -0.45980787 -0.20870582 -0.322

990
[[0.48599497 0.37060519 0.28103631 0.45266058 0.43939291 0.44174513
  0.20574597 0.23823474 0.39928375 0.18383246 0.11761564 0.14148772
  0.18080471 0.12175632 0.20311674 0.41060743 0.01993211 0.48348724
  0.07125658 0.37395855 0.02425941]]
[[0.48599497]
 [0.37060519]
 [0.28103631]
 [0.45266058]
 [0.43939291]
 [0.44174513]
 [0.20574597]
 [0.23823474]
 [0.39928375]
 [0.18383246]
 [0.11761564]
 [0.14148772]
 [0.18080471]
 [0.12175632]
 [0.20311674]
 [0.41060743]
 [0.01993211]
 [0.48348724]
 [0.07125658]
 [0.37395855]
 [0.02425941]]
991
[[-5.27673653e-01 -8.90185453e-02 -1.11259990e-01 -5.09553340e-01
  -9.77832047e-02 -9.35354317e-02 -4.06002662e-01 -5.21003858e-02
  -3.50971577e-01 -4.55065758e-01 -2.19981869e-01 -3.80579346e-04
  -1.31892030e-01 -2.94605477e-01 -2.41141583e-01 -3.59308821e-01
  -2.88315607e-01 -9.75615817e-02 -4.85180094e-01 -2.30403424e-01
  -3.28635151e-01]]
[[-5.27673653e-01]
 [-8.90185453e-02]
 [-1.11259990e-01]
 [-5.09553340e-01]
 [-9.77832047e-02]
 [-9.353543

IndexError: index 1000 is out of bounds for axis 0 with size 1000

In [65]:
print(W)
print(error_rate)

[[ 0.01583005]
 [-0.00324391]
 [ 0.02389098]
 [-0.01322724]
 [ 0.01095617]
 [-0.01529197]
 [ 0.00961821]
 [ 0.0275173 ]
 [-0.00810116]
 [ 0.01577052]
 [ 0.03813007]
 [ 0.01285487]
 [-0.00689867]
 [-0.00111542]
 [ 0.0265816 ]
 [ 0.03254792]
 [ 0.03422471]
 [-0.02078564]
 [ 0.03383118]
 [-0.00517123]
 [-0.01433324]]
0.475
