yujun shige dashuaige

In [1]:
import numpy as np

def sign(x):
    if x<=0:
        return -1
    if x>0:
        return 1

def getData(file_root):
    b=np.array(np.loadtxt(file_root))
    dataShape=b.shape
    xLen=b.shape[1]-1
    xNum=b.shape[0]
    X=b[:,0:xLen]
    Y=b[:,xLen:xLen+1]
    
    return X,Y
    
def getDataf(file_root):
    b=np.array(np.loadtxt(file_root))
    dataShape=b.shape
    xLen=b.shape[1]-1
    xNum=b.shape[0]
    X=b[:,0:xLen]
    #
    Xnew=np.ones((dataShape))
    Xnew[:,1:len(Xnew[0])]=X
    Y=b[:,xLen:xLen+1]
    
    return Xnew,Y



In [58]:
class Linear_Regression:
    
    def __init__(self):
        self._dimension = 0

    def fit(self, X, Y, lamb):
        self._dimension = len(X[0])
        self._w = np.zeros((self._dimension,1))
        self._lamb = lamb
        self._w = np.linalg.inv(np.dot(X.T, X) + lamb*np.eye(self._dimension)).dot(X.T).dot(Y)

    def predict(self, X):
        result = np.dot(X, self._w)
        return np.array([(1 if _ >= 0 else -1) for _ in result]).reshape(len(X), 1)

    def score(self, X, Y):
        Y_predict = self.predict(X)
        return sum(Y_predict!=Y)/(len(Y)*1.0)

    def get_w(self):
        return self._w

    def print_val(self):
        print ("w: ", self._w)


In [52]:
#Q13
#init
file_root_train='hw4_train.dat.txt'
file_root_test='hw4_test.dat.txt'
lamb=10

X_train, Y_train=getDataf(file_root_train)
X_test, Y_test=getDataf(file_root_test)

#function 
lr=Linear_Regression()
lr.fit(X_train,Y_train,lamb)
Ein = lr.score(X_train, Y_train)
print(Ein)

[0.05]


In [53]:
Eout=lr.score(X_test,Y_test)
print(Eout)

[0.045]


In [54]:
#Q14
list_lamb=[2,1,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10]
Einout=np.zeros((len(list_lamb),3))
for i in range(len(list_lamb)):
    lamb=lamb*(10**list_lamb[i])
    lr=Linear_Regression()
    lr.fit(X_train,Y_train,lamb)
    Einout[i][0]=lr.score(X_train, Y_train)
    Einout[i][1]=lr.score(X_test,Y_test)
    Einout[i][2]=list_lamb[i]

print(Einout)
print(list_lamb[np.argmin(Einout[:,1])])
print(np.argmin(list_lamb))

[[  0.46    0.511   2.   ]
 [  0.46    0.511   1.   ]
 [  0.46    0.511   0.   ]
 [  0.46    0.511  -1.   ]
 [  0.05    0.045  -2.   ]
 [  0.03    0.016  -3.   ]
 [  0.035   0.016  -4.   ]
 [  0.015   0.02   -5.   ]
 [  0.015   0.02   -6.   ]
 [  0.015   0.02   -7.   ]
 [  0.015   0.02   -8.   ]
 [  0.015   0.02   -9.   ]
 [  0.015   0.02  -10.   ]]
-3
12


In [55]:
#Q15
file_root_train='hw4_train.dat.txt'
file_root_test='hw4_test.dat.txt'
lamb=10
list_lamb=[2,1,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10]
Einout=np.zeros((len(list_lamb),3))
for i in range(len(list_lamb)):
    lamb=lamb*(10**list_lamb[i])
    lr=Linear_Regression()
    lr.fit(X_train,Y_train,lamb)
    Einout[i][0]=lr.score(X_train, Y_train)
    Einout[i][1]=lr.score(X_test,Y_test)
    Einout[i][2]=list_lamb[i]

print(Einout)
print(list_lamb[np.argmin(Einout[:,0])])
print(np.argmin(list_lamb))

[[  0.46    0.511   2.   ]
 [  0.46    0.511   1.   ]
 [  0.46    0.511   0.   ]
 [  0.46    0.511  -1.   ]
 [  0.05    0.045  -2.   ]
 [  0.03    0.016  -3.   ]
 [  0.035   0.016  -4.   ]
 [  0.015   0.02   -5.   ]
 [  0.015   0.02   -6.   ]
 [  0.015   0.02   -7.   ]
 [  0.015   0.02   -8.   ]
 [  0.015   0.02   -9.   ]
 [  0.015   0.02  -10.   ]]
-5
12


In [67]:
#Q16
file_root_train='hw4_train.dat.txt'
file_root_test='hw4_test.dat.txt'

lamb=10

X_train, Y_train= getDataf(file_root_train)
X_test, Y_test= getDataf(file_root_test)

X_tra=X_train[0:120,:]
Y_tra=Y_train[0:120,:]
X_val=X_train[120:,:]
Y_val=Y_train[120:,:]


list_lamb=[2,1,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10]
Einout=np.zeros((len(list_lamb),4))
for i in range(len(list_lamb)):
    lamb=10**list_lamb[i]
    lr=Linear_Regression()
    lr.fit(X_tra,Y_tra,lamb)
    Einout[i][0]=lr.score(X_tra, Y_tra)
    Einout[i][1]=lr.score(X_val,Y_val)
    Einout[i][2]=lr.score(X_test,Y_test)
    Einout[i][3]=list_lamb[i]

print(Einout)
print(list_lamb[np.argmin(Einout[:,1])])



[[ 3.41666667e-01  4.12500000e-01  4.14000000e-01  2.00000000e+00]
 [ 7.50000000e-02  1.25000000e-01  8.00000000e-02  1.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.80000000e-02  0.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.20000000e-02 -1.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.10000000e-02 -2.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.10000000e-02 -3.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.10000000e-02 -4.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.10000000e-02 -5.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.10000000e-02 -6.00000000e+00]
 [ 3.33333333e-02  3.75000000e-02  2.10000000e-02 -7.00000000e+00]
 [ 0.00000000e+00  5.00000000e-02  2.50000000e-02 -8.00000000e+00]
 [ 0.00000000e+00  1.00000000e-01  3.80000000e-02 -9.00000000e+00]
 [ 8.33333333e-03  1.25000000e-01  4.00000000e-02 -1.00000000e+01]]
0


In [68]:
lamb=0
lr=Linear_Regression()
lr.fit(X_train,Y_train,lamb)
print(lr.score(X_train, Y_train))
print(lr.score(X_test,Y_test))


[0.015]
[0.02]


In [81]:
#Q16
file_root_train='hw4_train.dat.txt'
file_root_test='hw4_test.dat.txt'

lamb=10

X_train, Y_train= getDataf(file_root_train)
X_test, Y_test= getDataf(file_root_test)
list_lamb=[2,1,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10]
Einout=np.zeros((len(list_lamb),4))

foldNum=5
start=0
end=40

for i in range(foldNum):
    X_val=X_train[start:end,:]
    X_tra=np.concatenate((X_train[0:start,:],X_train[end:,:]))
    Y_val=Y_train[start:end,:]
    Y_tra=np.concatenate((Y_train[0:start,:],Y_train[end:,:]))
    for j in range(len(list_lamb)):
        lamb=10**list_lamb[j]
        lr=Linear_Regression()
        lr.fit(X_tra,Y_tra,lamb)
        Einout[j][0]+=lr.score(X_tra,Y_tra)
        Einout[j][2]+=lr.score(X_test,Y_test)
        Einout[j][1]+=lr.score(X_val,Y_val)
        Einout[j][3]=list_lamb[j]        
    start+=40
    end+=40

for k in range(len(list_lamb)):
    Einout[k][0]/=5
    Einout[k][1]/=5
    Einout[k][2]/=5

print(Einout)

[[  0.26875   0.29      0.2914    2.     ]
 [  0.0625    0.06      0.0552    1.     ]
 [  0.0275    0.035     0.0206    0.     ]
 [  0.0275    0.035     0.0166   -1.     ]
 [  0.0275    0.035     0.0162   -2.     ]
 [  0.0275    0.035     0.0162   -3.     ]
 [  0.0275    0.035     0.0162   -4.     ]
 [  0.0275    0.035     0.0162   -5.     ]
 [  0.0275    0.035     0.0162   -6.     ]
 [  0.025     0.035     0.016    -7.     ]
 [  0.01625   0.03      0.019    -8.     ]
 [  0.02125   0.05      0.0216   -9.     ]
 [  0.02125   0.05      0.0218  -10.     ]]


In [84]:
lamb=10**-8
file_root_train='hw4_train.dat.txt'
file_root_test='hw4_test.dat.txt'

X_train, Y_train= getDataf(file_root_train)
X_test, Y_test= getDataf(file_root_test)
lr=Linear_Regression()
lr.fit(X_train,Y_train,lamb)
print(lr.score(X_train, Y_train))
print(lr.score(X_test,Y_test))

[0.015]
[0.02]
